CREATE TABLE goal_manual_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL REFERENCES goal(id) ON DELETE CASCADE,
    year_month VARCHAR(7) NOT NULL,
    amount NUMERIC(20, 2) NOT NULL,
    CONSTRAINT uk_goal_manual_contribution_goal_year UNIQUE (goal_id, year_month)
);
